- name: Install php libraries
  dnf:
    name:
      - php-fpm
      - php-mysqli
      - php-json
      - php
      - php-devel
    state: latest

- name: Install mariadb
  dnf:
    name: mariadb
    state: latest

- name: Download the wordpress package
  get_url:
    url: http://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Unarchive the wordpress package
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy the files and directories of wordpress
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: true
    owner: apache
    group: apache
